### ISSUE TITLE
Explain in the README that if you want to use Mackup, Mac username needs to be consistant.

### ISSUE THREAD

**Issue by borisschapira** [nhoizey/macOS-init#5]
I used the script to install my new Mac and nothing happend as expected. Not because of the script concepts, which are perfect, but because when my MBA asked me who is was, I did not answer the same thing that before. Therefore, on my new MBA, I was 'borisschapira' whereas I was 'boris' on my last one. Nearly nothing… except that Mackup f**ked up pretty bad trying to restore my preferences, trying to build symlinks to `/Users/boris/` where only `/User/borisschapira` existed…

**Comment by nhoizey** [comment]
I'll add a note about that, thanks.

Did you search Mackup to know if they're aware of the issue?

**Comment by borisschapira** [comment]
They can't do anything about it. The solution is for backup and restore, not for installation upon heterogeneous configurations. Same thing for the apps backuped data: it often contains absolute strings that point to specific folders on the computer. Change the current username, and everything falls apart. Hopefully, there is a built-in feat in mac OS that allow you to change your username *and* I'm versed enough into CLI scripting to make a script that change all the symlinks that pointed to `/Users/borisschapira/` to `/Users/boris/`. `find` has intimated me for years, now he's my best friend 👍
