### ISSUE TITLE
Mauvaises double quote

### ISSUE THREAD

**Issue by benoitbesnard** [nhoizey/macOS-init#6]
https://github.com/nhoizey/macOS-init/blob/245dcbb3efcf65836376968463bb01877f471d35/post-cloud.sh#L14

Cette ligne ne fonctionne pas à cause des guillemets

**Comment by nhoizey** [comment]
@benoitbesnard presque 5 ans plus tard, je n'étais pas passé par les issues, et il semble que celle-ci soit déjà corrigée… 😅

Désolé ! 😔

**Comment by benoitbesnard** [comment]
Effectivement :wink:  je n'ai plus de mac depuis donc ce n'est pas très grave :smile:
